### PR TITLE
Fix dependencies between resources

### LINKED ISSUE #73: Creating SNS resource simultaneously results in error " Error: creating Backup Vault Notifications (): AccessDeniedException: "
Add a sns.tf with the following content:

```
resource "aws_sns_topic" "sample_topic" {
  name = "sample name"
  kms_master_key_id = "alias/aws/sns"

  tags = merge(
    var.tags,
    {
      Name = "sample tag name"
    }
  )
}

resource "aws_sns_topic_subscription" "sample_subscription" {
  topic_arn = aws_sns_topic.sample_topic.arn
  protocol  = "email"
  endpoint  = "user@email.com"
}
```

And configure main.tf notificacions as:

```
  notifications = {
    sns_topic_arn       = aws_sns_topic.sample_topic.arn
    backup_vault_events = ["BACKUP_JOB_STARTED", "BACKUP_JOB_COMPLETED", "BACKUP_JOB_FAILED", "RESTORE_JOB_COMPLETED", "COPY_JOB_STARTED", "COPY_JOB_SUCCESSFUL", "COPY_JOB_FAILED"]
  }
```
Results in:

│ Error: creating Backup Vault Notifications (): AccessDeniedException: 
│       status code: 403, request id: 6bcd24a3-edce-4d16-8695-3fea790fabf8
│ 
│   with module.sample_backup.aws_backup_vault_notifications.backup_events[0],
│   on .terraform/modules/sample_backup/notifications.tf line 25, in resource "aws_backup_vault_notifications" "backup_events":
│   25: resource "aws_backup_vault_notifications" "backup_events" {
│ 

Adding a depends_on in the notificacions.tf file allows to create SNS topic/subscriptions alongside the afformented backup:

` depends_on = `[aws_backup_vault.ab_vault]`

### PR DESCRIPTION
**Pull request by dhoppe**
Closes #73

### CODE REVIEW

**Comment by dhoppe** [comment]
@lgallard Any chance to get this merge, soon?

**Comment by lgallard** [comment]
@dhoppe thanks for your PR. I would like to have more context on this one to understand the changes, probably by replicating #73. I will take a look at the issue and your solution before approving.

**Comment by lgallard** [comment]
@dhoppe I wasn't able to reproduce #73. Please, check the code I shared as comment in #73 and the possible option to overcome it in case it occurs.

If you have another example to reproduce #73, let me know. Meanwhile, I'm not going to merge this PR.

**Comment by dhoppe** [comment]
I use the latest version of your Terraform module and the Terraform AWS Provider, but I still get the following error message during the first execution. 

```
Plan: 12 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + plan_arn     = (known after apply)
  + plan_id      = (known after apply)
  + plan_role    = "aws-backup-plan-confluence-efs-dev-role"
  + plan_version = (known after apply)
  + vault_arn    = (known after apply)
  + vault_id     = (known after apply)
aws_backup_vault_notifications.backup_events[0]: Creating...
aws_iam_policy.ab_tag_policy[0]: Creating...
aws_backup_vault.ab_vault[0]: Creating...
aws_iam_role.ab_role[0]: Creating...
aws_sns_topic_policy.backup_events[0]: Creating...
aws_sns_topic_policy.backup_events[0]: Creation complete after 0s [id=arn:aws:sns:eu-west-1:_REDACTED_:atlassian-dev]
aws_backup_vault.ab_vault[0]: Creation complete after 0s [id=confluence-efs-dev]
aws_backup_plan.ab_plan[0]: Creating...
aws_iam_policy.ab_tag_policy[0]: Creation complete after 0s [id=arn:aws:iam::_REDACTED_:policy/terraform-20230316125608564500000001]
aws_iam_role.ab_role[0]: Creation complete after 1s [id=aws-backup-plan-confluence-efs-dev-role]
aws_iam_role_policy_attachment.ab_restores_policy_attach[0]: Creating...
aws_iam_role_policy_attachment.ab_policy_attach[0]: Creating...
aws_iam_role_policy_attachment.ab_restores_s3_policy_attach[0]: Creating...
aws_iam_role_policy_attachment.ab_tag_policy_attach[0]: Creating...
aws_iam_role_policy_attachment.ab_backup_s3_policy_attach[0]: Creating...
aws_backup_plan.ab_plan[0]: Creation complete after 1s [id=384fe60b-7795-4965-acac-c22fb303e76c]
aws_backup_selection.ab_selection[0]: Creating...
aws_iam_role_policy_attachment.ab_restores_policy_attach[0]: Creation complete after 0s [id=aws-backup-plan-confluence-efs-dev-role-20230316125609713000000002]
aws_iam_role_policy_attachment.ab_policy_attach[0]: Creation complete after 0s [id=aws-backup-plan-confluence-efs-dev-role-20230316125609747100000003]
aws_iam_role_policy_attachment.ab_backup_s3_policy_attach[0]: Creation complete after 0s [id=aws-backup-plan-confluence-efs-dev-role-20230316125609920700000005]
aws_iam_role_policy_attachment.ab_tag_policy_attach[0]: Creation complete after 0s [id=aws-backup-plan-confluence-efs-dev-role-20230316125609880800000004]
aws_iam_role_policy_attachment.ab_restores_s3_policy_attach[0]: Creation complete after 0s [id=aws-backup-plan-confluence-efs-dev-role-20230316125610055200000006]
aws_backup_selection.ab_selection[0]: Still creating... [10s elapsed]
aws_backup_selection.ab_selection[0]: Creation complete after 16s [id=8651407d-fda3-4f9d-9a96-ab002eca6bff]
╷
│ Error: creating Backup Vault Notifications (): AccessDeniedException:
│     status code: 403, request id: 2798bf61-078a-444c-99c5-44351c6ff72e
│
│   with aws_backup_vault_notifications.backup_events[0],
│   on notifications.tf line 25, in resource "aws_backup_vault_notifications" "backup_events":
│   25: resource "aws_backup_vault_notifications" "backup_events" {
│
╵
Releasing state lock. This may take a few moments...
ERRO[0253] Terraform invocation failed in /Users/dhoppe/Customers/_REDACTED_/terragrunt-aws-atlassian/stacks/dev/eu-west-1/confluence/backup-efs/.terragrunt-cache/Ro3DBHOF6qpDMG2Jsl9ycjgJsFQ/_-OUS7IrbkPEuqn34kmlQEv67F8  prefix=[/Users/dhoppe/Customers/_REDACTED_/terragrunt-aws-atlassian/stacks/dev/eu-west-1/confluence/backup-efs]
ERRO[0253] Module /Users/dhoppe/Customers/_REDACTED_/terragrunt-aws-atlassian/stacks/dev/eu-west-1/confluence/backup-efs has finished with an error: 1 error occurred:
    * exit status 1
  prefix=[/Users/dhoppe/Customers/_REDACTED_/terragrunt-aws-atlassian/stacks/dev/eu-west-1/confluence/backup-efs]
ERRO[0253] 1 error occurred:
    * exit status 1
```

During the second execution everything works as expected, but I did not had this issue using my pull request. 
```
Terraform will perform the following actions:

  # aws_backup_vault_notifications.backup_events[0] will be created
  + resource "aws_backup_vault_notifications" "backup_events" {
      + backup_vault_arn    = (known after apply)
      + backup_vault_events = [
          + "BACKUP_JOB_COMPLETED",
        ]
      + backup_vault_name   = "confluence-efs-dev"
      + id                  = (known after apply)
      + sns_topic_arn       = "arn:aws:sns:eu-west-1:_REDACTED_:atlassian-dev"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
aws_backup_vault_notifications.backup_events[0]: Creating...
aws_backup_vault_notifications.backup_events[0]: Creation complete after 0s [id=confluence-efs-dev]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Comment by dhoppe** [comment]
I use the following config.

\_common/confluence/backup-efs.hcl:
```
terraform {
  source = "${local.terraform_source}//.?version=0.19.0"
}

dependency "atlassian_sns" {
  config_path  = "${get_terragrunt_dir()}/../../atlassian/sns"
  mock_outputs = yamldecode(file("${get_repo_root()}/_mocks/sns.yaml"))
}

dependency "confluence_efs" {
  config_path  = "${get_terragrunt_dir()}/../../confluence/efs"
  mock_outputs = yamldecode(file("${get_repo_root()}/_mocks/efs.yaml"))
}

dependency "confluence_kms-efs" {
  config_path  = "${get_terragrunt_dir()}/../../confluence/kms-efs"
  mock_outputs = yamldecode(file("${get_repo_root()}/_mocks/kms.yaml"))
}

locals {
  environment_vars = read_terragrunt_config(find_in_parent_folders("env.hcl"))
  env_name         = local.environment_vars.locals.environment

  terraform_source = "tfr:///lgallard/backup/aws"
}

inputs = {
  vault_name        = "confluence-efs-${local.env_name}"
  vault_kms_key_arn = dependency.confluence_kms-efs.outputs.key_arn

  plan_name = "confluence-efs-${local.env_name}"

  selections = [
    {
      name = "confluence-efs-${local.env_name}"
      resources = [
        dependency.confluence_efs.outputs.aws_efs_file_system_arn
      ]
    }
  ]

  notifications = {
    sns_topic_arn = dependency.atlassian_sns.outputs.topic_arn
    backup_vault_events = [
      "BACKUP_JOB_COMPLETED"
    ]
  }
}
```

stacks/dev/eu-west-1/confluence/backup-efs/terragrunt.hcl:
```
include "root" {
  path = find_in_parent_folders()
}

include "common" {
  path = "${dirname(find_in_parent_folders())}/_common/confluence/backup-efs.hcl"
}

inputs = {
  vault_force_destroy = true

  rules = [
    {
      name              = "backup_full"
      schedule          = "cron(0 2 ? * * *)"
      start_window      = "60"
      completion_window = "120"

      lifecycle = {
        cold_storage = 0
        delete_after = 10
      }

      recovery_point_tags = {
        Backup-Type = "Daily"
      }
    },
    {
      name              = "backup_incr"
      schedule          = "cron(0 */4 ? * * *)"
      start_window      = "60"
      completion_window = "120"

      lifecycle = {
        cold_storage = 0
        delete_after = 2
      }

      recovery_point_tags = {
        Backup-Type = "Incremental"
      }
    }
  ]
}
```

I only tested my own pull request, because it does not make sense to use `depends_on`. This is not even recommended by HashiCorp. 

> You should use depends_on as a last resort because it can cause Terraform to create more conservative plans that replace more resources than necessary. For example, Terraform may treat more values as unknown “(known after apply)” because it is uncertain what changes will occur on the upstream object. This is especially likely when you use depends_on for modules.

**Comment by lgallard** [comment]
@dhoppe the `depend_on` is between an external resources (SNS topic) and this module. In any case, your PR can help in improving how the Terraform plan is generated internally, so I'm merging it as [stated in the documentation](https://developer.hashicorp.com/terraform/language/meta-arguments/depends_on#:~:text=we%20recommend%20using%20expression%20references).

Thanks for your PR!

**Pull request merged**
